### ISSUE TITLE
get-token and seed not working

### ISSUE THREAD

**Issue by dantxal** [sibelius/relay-workshop#11]
# Bug
```

MongoError: command find requires authentication
    at Connection.<anonymous> 

(node:308697) UnhandledPromiseRejectionWarning: MongoError: command find requires authentication
    at Connection.<anonymous> (/home/dantxal/projects/study/relay-workshop/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:310:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/home/dantxal/projects/study/relay-workshop/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (/home/dantxal/projects/study/relay-workshop/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:308697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:308697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment info

I am running `yarn server` with the following environment variables.
```
PORT=7500
MONGO_URI=mongodb+srv://sibelius:eYZlo2POmcyuUuRR@reacteurope-los0c.mongodb.net/test
```

## Steps To Reproduce

Describe what you expected to happen:

With the server running, if you try either of the commands: `yarn get-token` or `yarn seed`; You will see the error.

1. Run server with `yarn server` (a good way to reproduce is using the provided mongo uri).

2. Then try to run `yarn seed` or `yarn get-token`

## Reproducible sample code

Only set environment variables.

## Additional Information

I also got the same error when trying to run it with a local server of mongo (running inside a docker container). 

My mongo uri did include the 'user:password' part.

## Possible workaround for now

1. Load playground at `http://localhost:7500/graphiql`

2. Register a new user using the query:
```
mutation {
  UserRegisterWithEmail(input: {
    email: "validemail@test.com"
    password: "123456"
    name: "Valid Name"
  }) {
    token
    me {
      id
      name
      email
    }
  }
}

```
3. Copy the token you will get `JWT RANDOM_HASH`.

Next step are for anyone trying to complete workshop lessons that need authorization.

4. Paste the token inside function `getToken` in `fetchGraphQL.tsx` .

```
const getToken = () => {
  /**
   * TODO
   * use your user token
   */
  return 'JWT paste_your_token_here';
};
```

**Comment by sibelius** [comment]
I think this mongo_uri is not valid anymore

the best way is to update readme/documentation to get mongo running locally or using your own Mongo Atlas instance

**Comment by dantxal** [comment]
I found a possible way to solve this.

I was setting up seeds for my server and started getting the same error. 
What you can do is **provide 'user', 'pass' and 'authSource'** on `mongoose.connect` method. 

```
mongoose.connect(MONGO_URI, {
      user: 'admin',
      pass: 'example',
      authSource: 'admin',
      ...other options
    } as ConnectionOptions);
```

And if you're running 'mongo' image on docker. Run it using '--auth' option. According to 

```
docker run --name some-mongo 
-e MONGO_INITDB_ROOT_USERNAME=admin 
-e MONGO_INITDB_ROOT_PASSWORD=example 
-d -p 27017:27017 
mongo --auth
```

If you want additional information, you can check: 
https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-auth
https://hub.docker.com/_/mongo

I will be closing this issue for now.
