### ISSUE TITLE
TypeError: Class constructor GraphQLNonNull cannot be invoked without 'new'

### ISSUE THREAD

**Issue by EmanuelCampos** [sibelius/relay-workshop#1301]
Error appearing after the basic setup

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/16262455/164217266-49fda4ef-594b-48fd-bb8a-c41962c6b561.png">

**Comment by sibelius** [comment]
send the fix to graphql-relay-subscription

**Comment by sibelius** [comment]
fixed
