### ISSUE TITLE
Typo on server's package.json

### ISSUE THREAD

**Issue by joao-pedrozo** [sibelius/relay-workshop#220]
# Bug

Sup guys, in the main `README` is said that to run the server we need to execute the follow command: `yarn server`. But looking out our `package.json` inside the `packages/server`, it seems that the most similar command is `yarn serve`. Maybe a typo? I don't know exactly the reason of being written like that, or if am I in the wrong place to run the server, what you guys think? :smile:

**Comment by sibelius** [comment]
What about in package.json on the root?

**Comment by sibelius** [comment]
not a typo

https://github.com/sibelius/relay-workshop/blob/master/package.json#L107
