### ISSUE TITLE
preloadQueries is deprecated 

### ISSUE THREAD

**Issue by simkessy** [sibelius/relay-workshop#310]
This export is no longer available in react-relay/hooks

**Comment by sibelius** [comment]
preloadQuery -> loadQuery

**Comment by simkessy** [comment]
I tried loadQuery but it returns an object instead of a function

![image](https://user-images.githubusercontent.com/5871660/107285099-c6a34600-6a02-11eb-815d-3d140f7e99f3.png)

**Comment by sibelius** [comment]
check this hacky https://github.com/sibelius/relay-workshop/blob/master/packages/relay/src/loadQuery.tsx#L2

**Comment by simkessy** [comment]
Seems like another issue now

![Uploading image.png…]()

**Comment by sibelius** [comment]
it looks like a mismatch of relay compiler and relay runtime

**Comment by simkessy** [comment]
I'm using: 
    "react-relay": "^0.0.0-experimental-4c4107dd",
    "relay-runtime": "^10.1.3",

Can the workshop be updated with  a working version of these tests?

**Comment by sibelius** [comment]
is the workshop tests breaking?
