### ISSUE TITLE
yarn 2 

### ISSUE THREAD

**Issue by sibelius** [sibelius/relay-workshop#83]
Let's migrate to yarn 2

**Comment by mickdelaney** [comment]
Is this still planned ?
How much work is involved in the migration ?

**Comment by sibelius** [comment]
There is yarn 3 now

We need to play and see if it is worth it

**Comment by Tsugami** [comment]
yarn v2 and v3 use pnp, dependabot does not have upnp support

**Comment by sibelius** [comment]
we could have yarn 3 without pnp

is it worth ?

**Comment by Tsugami** [comment]
> we could have yarn 3 without pnp
> 
> is it worth ?

I think the best feature of yarn 3v and 2v is the pnp, I don't know if it's worth using without php, I' don't know if has as well.

**Comment by sibelius** [comment]
I think yarn v2/3 could be faster and more reliable, it is worth trying

**Comment by fersilva16** [comment]
> yarn v2 and v3 use pnp, dependabot does not have upnp support

[Renovate](https://github.com/renovatebot/renovate) have yarn v2/3 support, but I don't if it's a good bot

**Comment by tgmarinho** [comment]
it's better to migrate to turborepo and pnpm. I can work on it.

**Comment by sibelius** [comment]
does pnpm works with dependabot?

**Comment by enriquebeta6** [comment]
[Dependabot supports pnpm](https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/)

**Comment by sibelius** [comment]
Bun?

**Comment by sibelius** [comment]
pnpm works
