### ISSUE TITLE
Migration to entria-mongoose-helpers and entria-mongoose-loader

### ISSUE THREAD

**Issue by Tsugami** [sibelius/relay-workshop#836]
# Feature Request
Migrate all codebase to entria-mongoose-helpers and entria-mongoose-loader, some parts are are using but need to migrate 100%

https://github.com/entria/graphql-mongo-helpers
https://github.com/entria/graphql-mongoose-loader

## Why it is needed
the libs are totaly based in this project, a better method of find out if the libs are ok is using here, straight from the source

**Comment by sibelius** [comment]
codemod ?
