### ISSUE TITLE
TypeError environment.getStore().getEpoch is not a function

### ISSUE THREAD

**Issue by LeAlencar** [sibelius/relay-workshop#955]
# Question

I'm receiving this error in exercise 02-useLazyLoadQuery and actually don't know where to find any solution to it. 
I even check the solution and tried to use yours to see if was an error in the code that I created, but the error continues.

**Comment by LeAlencar** [comment]
![image](https://user-images.githubusercontent.com/52898510/149199719-a0c8060a-99cc-4f5b-9639-1036db2db187.png)

**Comment by sibelius** [comment]
try to make sure you have the right version for all relay packages

- yarn why react-relay
- yarn why relay-runtime

**Comment by LeAlencar** [comment]
react-relay@12.0.0 in 15 dependencies.
relay-runtime@11.0.2 in 13 dependencies.

**Comment by sibelius** [comment]
can you update it all to latest v12?

**Comment by LeAlencar** [comment]
is there a way to upgrade every package at once?

**Comment by LeAlencar** [comment]
updating the relay-runtime into web package to latest v12 fix the error.
